# Hello World
GET http://localhost:3000

###
# Create user
POST http://localhost:3000/api/users/create
Content-Type: application/json

{
    "email": "demo@demo.com",
    "password": "password"
}

###
# Login
# @name login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "demo@demo.com",
    "password": "password"
}

###
# Get transactions
@jwt = {{login.response.body.token}}
GET http://localhost:3000/api/transactions
Authorization: Bearer {{jwt}}

###
# Create transaction
@jwt = {{login.response.body.token}}
POST http://localhost:3000/api/transactions
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "date": "2021-01-01",
    "action": "B",
    "asset": "ETH",
    "count": 10,
    "price": 1000,
    "fee": 0.0
}

###
# Update transaction
@jwt = {{login.response.body.token}}
PATCH http://localhost:3000/api/transactions/4
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "fee": 1.0
}

###
# Delete transaction
@jwt = {{login.response.body.token}}
DELETE http://localhost:3000/api/transactions/4
Authorization: Bearer {{jwt}}

###
